In [8]:
# task1 用 numpy 创建一个 2 * 2 的二维数组 ndarray，指定元素类型为 float，命名为 arr1（阅读参考文章⑤）
import numpy as np
arr1 = np.array([(1,2),(3,4)], dtype = np.float64)
print('arr1:\n',arr1)

arr1:
 [[1. 2.]
 [3. 4.]]


In [14]:
# task2 生成元素全为 0 的 6 * 6 矩阵 arr2；元素全为 1 的 6 * 6 矩阵 arr3；以及 6 * 6 的单位矩阵 arr4（任务提示：单位矩阵对角线元素为 1，阅读参考文章⑥）
import numpy as np
arr = np.arange(36).reshape(6,6)
arr2 = np.zeros_like(arr)
arr3 = np.ones_like(arr)
arr4 = np.eye(6)
print(f'arr:\n{arr}\narr2:\n{arr2}\narr3:\n{arr3}\narr4:\n{arr4}\n')

arr:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
arr2:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
arr3:
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
arr4:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]



In [18]:
#task3 运用 arange 函数生成生成 [0, 10) 区间内，步长为 2 的整数序列 arr5（阅读参考文章⑦）
import numpy as np
arr5 = np.arange(0,10,2)
print(f'arr5:\n{arr5}\n')

arr5:
[0 2 4 6 8]



In [20]:
#tast4 生成 0~10 间的等差数列 arr6，元素个数为 6（任务提示：等差数列函数为 linspace，阅读参考文章⑧）
import numpy as np
arr6 = np.linspace(0,10,6) # endpoint = True 
print(f"arr6:\n{arr6}")

arr6:
[ 0.  2.  4.  6.  8. 10.]


In [31]:
#task5 创建一个长度为 10 的随机数组（每个元素都是整数）并将最大值替换为 0（任务提示：numpy 随机函数为 random，利用 argmax() 得到数组最大值的位置，然后再将此位置数字利用切片替换，阅读参考文章⑨⑩）
# https://blog.csdn.net/jinxiaonian11/article/details/53143141
import numpy as np
arr7 = np.random.randint(1,100,10)
print(f'arr7:\n{arr7}')
arr7[np.argmax(arr7)] = 0
print(f'arr7:\n{arr7}')

arr7:
[74 33 87 57 65 13 23 80 92  6]
arr7:
[74 33 87 57 65 13 23 80  0  6]


In [33]:
#task6 计算数组 x = np.array([1,2,3,2,3,4,3,4,5,6]) 和数组 y = np.array([7,2,10,2,7,4,9,4,9,8]) 之间的欧式距离
# 计算Python Numpy向量之间的欧氏距离 https://blog.csdn.net/qq_35531549/article/details/88913724
import numpy as np
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
dist1 = np.sqrt(np.sum(np.square(x-y)))
dist2 = np.linalg.norm(x-y)
print(f'dist1:\n{dist1}')
print(f'dist2:\n{dist2}')

dist1:
12.529964086141668
dist2:
12.529964086141668


In [4]:
!conda info --envs
!activate base
!pip install matplotlib

# conda environments:
#
base                  *  C:\Users\Shawn Yan\anaconda3



In [5]:
#tast8 附加题（不作为任务要求）计算 任务7 中资金价值的最大回撤
#（提示1：最大回撤是指投资组合在选定的周期内，任一时间点往后推，可能出现资产净值下降的最大幅度。简单举例，例如某年连续开盘日 9 天，净值分别为 x=[1,0.5,5.0,2.5,4.0,3.0,2.5,1,2] 则该段时间最大回撤为（5-1），而不是最高值 5 与最低值 0.5 的差，如下图。 

#提示2：最大回撤计算公式为 max_drawdown = np.max(np.maximum.accumulate(values) - values)，阅读参考文章⑫⑬）

import numpy as np
import matplotlib.pyplot as plt
def MaxDrawdown(return_list):
    '''最大回撤率'''
    i = np.argmax((np.maximum.accumulate(return_list) - return_list) / np.maximum.accumulate(return_list))  # 结束位置
    if i == 0:
        return 0
    j = np.argmax(return_list[:i])  # 开始位置
    return (return_list[j] - return_list[i]) / (return_list[j])
 
return_list=[12,12,21,15,27,16,21,22,25,20,16,17]
print(MaxDrawdown(return_list))



ModuleNotFoundError: No module named 'matplotlib'

In [6]:
!conda info --envs

# conda environments:
#
base                  *  C:\Users\Shawn Yan\anaconda3

